version: "3"
services:
  db:
    container_name: postgres_database
    image: postgres:16.2-alpine
    volumes:
# - postgres-db:/var/lib/postgresql/data # ejemplo con volumen creado 
      - ./postgres:/var/lib/postgresql/data # bind volume, './' path relativo al archivo 
    environment:
      - POSTGRES_PASSWORD=123456

  pgAdmin:
    depends_on:
      - db
    container_name: pg_admin
    image: dpage/pgadmin4:8
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin #bind volume para persistir info de pgadmin 
    environment:
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=ponchovalo@outlook.com

#volumes: 

#  postgres-db: 

#    external: true 
